version: '3.1'
services:
  env:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/project
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    stdin_open: true
    tty: true
