version: '3.1'
services:
  env:
    image: sajjikazemi/scptoolbox:1.0.0
    working_dir: /project
    container_name: dublin
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/project
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    stdin_open: true
    tty: true
